#!/usr/bin/env bash

echo -n 'Enter an animal sound : '
read sound;

echo -n 'Enter a small animal : '
read small;

echo -n 'Enter a large animal : '
read large;

echo ""
echo ""
echo "Dog goes $sound,"
echo "$small goes meow,"
echo "Bird goes tweet,"
echo "and $large goes squeak."
